"use client"

import { useRef } from "react"
import { motion, useInView } from "framer-motion"
import Image from "next/image"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Headphones, FileText, Sparkles } from "lucide-react"

export function FeaturedSection() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, amount: 0.2 })

  const features = [
    {
      icon: <Sparkles className="h-6 w-6 text-primary" />,
      title: "AI-Powered Summaries",
      description: "Get concise summaries of every article generated by our advanced AI technology.",
    },
    {
      icon: <Headphones className="h-6 w-6 text-primary" />,
      title: "Audio Versions",
      description: "Listen to articles on the go with high-quality text-to-speech conversion.",
    },
    {
      icon: <FileText className="h-6 w-6 text-primary" />,
      title: "Premium PDFs",
      description: "Access in-depth resources and extended content through our premium PDF library.",
    },
  ]

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  }

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.5 },
    },
  }

  return (
    <section ref={ref} className="py-16 md:py-24 bg-muted/30">
      <div className="container">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div>
            <Badge className="mb-4" variant="outline">
              Premium Features
            </Badge>
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl mb-6">Elevate Your Reading Experience</h2>
            <p className="text-muted-foreground mb-8 text-lg">
              Our platform combines cutting-edge AI technology with premium content to provide you with the best reading
              experience possible.
            </p>

            <motion.div
              variants={containerVariants}
              initial="hidden"
              animate={isInView ? "visible" : "hidden"}
              className="space-y-6"
            >
              {features.map((feature, index) => (
                <motion.div key={index} variants={itemVariants}>
                  <Card className="border-2">
                    <CardContent className="p-6 flex gap-4">
                      <div className="mt-1">{feature.icon}</div>
                      <div>
                        <h3 className="font-semibold text-lg mb-1">{feature.title}</h3>
                        <p className="text-muted-foreground">{feature.description}</p>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </motion.div>
          </div>

          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={isInView ? { opacity: 1, scale: 1 } : { opacity: 0, scale: 0.9 }}
            transition={{ duration: 0.7 }}
            className="relative aspect-square md:aspect-auto md:h-[600px] rounded-2xl overflow-hidden"
          >
            <Image src="/placeholder.svg?height=1200&width=800" alt="Featured content" fill className="object-cover" />
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
            <div className="absolute bottom-0 left-0 right-0 p-8">
              <Badge className="bg-primary text-primary-foreground mb-3">Featured</Badge>
              <h3 className="text-2xl font-bold text-white mb-2">The Future of Content Creation</h3>
              <p className="text-white/80">
                Discover how AI is transforming the way we create and consume content in 2023.
              </p>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
